---
engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
        - .js
        - .jsx
  stylelint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.scss"
exclude_paths:
  - coverage/**/*
  - dist/**/*
  - node_modules/**/*
  - test/**/*
