name: CI

on:
  push:
    branches: ['main']
    tags: ['v*"']
  pull_request:
    branches: ["*"]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate and Deploy
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Sao_Paulo

      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Packages
        run: pnpm install
        timeout-minutes: 3

      - name: Validate and Build
        run: pnpm run validate
        timeout-minutes: 3

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: 'colormeup'
          server: 'colormeup.co'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist'
          remote_path: '/srv/users/colormeup/apps/colormeup/public'
