name: Quality Assurance

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['*']

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Sao_Paulo

      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Packages
        run: pnpm install
        timeout-minutes: 3

      - name: Run Linting
        run: pnpm run lint
        timeout-minutes: 2

      - name: Run Stylelint
        run: pnpm run lint:styles
        timeout-minutes: 2

      - name: Run Type Checking
        run: pnpm run typecheck
        timeout-minutes: 2

      - name: Run Unit Tests with Coverage
        run: pnpm run test:coverage
        timeout-minutes: 3

      - name: Build Project
        run: pnpm run build
        timeout-minutes: 2

      - name: Run size-limit
        run: pnpm run size
        timeout-minutes: 2
